# Generated by Django 4.0.6 on 2023-07-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_options'),
        ('shopapp', '0008_rename_user_product_created_by'),
    ]

    operations = [
    ]
